version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: gossip-mun-uz-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "127.0.0.1:${MONGODB_EXPOSE}:${MONGODB_PORT}"
    networks:
      - app-network
    command: mongod --port ${MONGODB_PORT}

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gossip-mun-uz-backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "127.0.0.1:${BACKEND_EXPOSE}:${BACKEND_PORT}"
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=mongodb://mongodb:${MONGODB_PORT}/gossip
      - CORS_ORIGIN=https://gossip.ytech.space
      - PORT=${BACKEND_PORT}
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gossip-mun-uz-frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "127.0.0.1:${FRONTEND_EXPOSE}:${FRONTEND_PROD_PORT}"
      # - "${FRONTEND_EXPOSE}:${FRONTEND_DEV_PORT}"
    environment:
      - VITE_API_URL=https://gossip.ytech.space/api
      - VITE_SOCKET_URL=https://gossip.ytech.space
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: