version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: gossip-mun-uz-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gossip-mun-uz-backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gossip-mun-uz-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      # - "8080:80"
      - "8080:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_SOCKET_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: